name: build

on: [push]

jobs:
  mxe32:
    name: Windows 32-bit (MXE Cross Build)
    runs-on: ubuntu-18.04
    continue-on-error: false
    env:
      CFLAGS: -std=c11
      CXXFLAGS: -std=c++11
    steps:
    - uses: actions/checkout@v2

    - name: Add MXE Repository to Apt
      uses: myci-actions/add-deb-repo@4
      with:
        repo: deb http://pkg.mxe.cc/repos/apt bionic main
        repo-name: mxe
        keys: 86B72ED9
        key-server: keyserver.ubuntu.com

    - name: Install MXE Build Environment
      run: |
        sudo apt update
        sudo apt install \
          nasm \
          libtool \
          libtool-bin \
          gperf \
          lzip \
          p7zip-full \
          intltool \
          mxe-i686-w64-mingw32.static-cc \
          mxe-i686-w64-mingw32.static-cairo \
          mxe-i686-w64-mingw32.static-pango \
          mxe-i686-w64-mingw32.static-jpeg \
          mxe-i686-w64-mingw32.static-glew \
          mxe-i686-w64-mingw32.static-freetype \
          mxe-i686-w64-mingw32.static-curl \
          mxe-i686-w64-mingw32.static-librtmp \
          mxe-i686-w64-mingw32.static-ffmpeg \
          mxe-i686-w64-mingw32.static-sdl2-mixer
        echo /usr/lib/mxe/usr/bin >> $GITHUB_PATH  # exposes it to all future steps

    - name: Run MXE Build
      run: |
        sudo tar -xz -f "unrtf-0.21.9.tar.gz"
        cd "unrtf-0.21.9"
        sudo autoreconf -i
        sudo ./configure --host=i686-w64-mingw32.static
        sudo make
        #sudo ls -R
        #sudo cp src/unrtf unrtf.exe
        sudo chmod a=r ./src/

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "unrtf"
        path: ./src/
